#!/bin/bash
# This is an attempt to make chroot progress much easier for newuser

if [[ -z $1 ]]; then
  echo " USAGE: terraroot <chroot-directory>"
    return 1
fi

mount -t proc proc $1/proc
mount -o bind /dev $1/dev
mount -o bind /sys $1/sys
mount -o bind /dev/pts $1/dev/pts

echo 'mounting done, now entering chroot | Type exit when you donw'

chroot $1

umount $1/{dev/pts,dev,sys,proc} || return 1
